### ISSUE TITLE
qtexample throws error on failed assertion

### ISSUE THREAD

**Issue by anne-gropler** [cginternals/globjects#378]
Set up globjects from master, use glbinding from master, then start the qtexample application.

Execution stops at glbinding::Function.inl::246:
`assert(AbstractFunction::maxPos() >= pos);` because pos is 0 and maxPos returns -1.

Stack:
>glbindingd.dll!glbinding::Function<void,enum gl::ClearBufferMask>::state(int pos) line 246 glbindingd.dll!glbinding::Function<void,enum gl::ClearBufferMask>::state() line 241
 glbindingd.dll!glbinding::AbstractFunction::address() line 53
 glbindingd.dll!glbinding::Function<void,enum gl::ClearBufferMask>::call(gl::ClearBufferMask & <arguments_0>) line 149
 glbindingd.dll!glbinding::Function<void,enum gl::ClearBufferMask>::operator()(gl::ClearBufferMask & <arguments_0>) line 144
 glbindingd.dll!gl::glClear(gl::ClearBufferMask mask) line 62
 qtexampled.exe!Window::paintGL() line116
 qtexampled.exe!WindowQt::paint() line120
 qtexampled.exe!WindowQt::exposeEvent(QExposeEvent * __formal) line 79
...

Is this a bug? Or a configuration error with glbinding? If the latter, how to I configure it correctly?

I am working on Windows 10, MVS 2017 (Version 15.8.6), setup with CMake 3.12.3 and Qt 5.11.2.

**Comment by anne-gropler** [comment]
Checkout master, use glbinding from master (timestamp for both: 25.10.2018 14:30).
Start qtexample of globjects, compiler error C2665 on line https://github.com/cginternals/globjects/blob/1a0abe5f866202369860f9e7b2d09c1c7d6e8638/source/examples/qtexample/main.cpp#L51
Same for qtexample-ex.

**Comment by scheibel** [comment]
This commit should at least fix the compilation error.

**Comment by anne-gropler** [comment]
Both problems are fixed, thanks a lot! :)
